from bs4 import BeautifulSoup
import requests
import spotipy
from spotipy.oauth2 import SpotifyOAuth

date_input = input("Which Year would you like to travel to? Type the date in this format YYYY-MM-DD: ")

URL = f"https://www.billboard.com/charts/hot-100/{date_input}"
SPOTIFY_ID = "729651bb0b0e455189acc585b17a3c8f"
SPOTIFY_SECRET = "3c75a2e165e54d98926fe8b712a472cb"

response = requests.get(url=URL, timeout=60)
info = response.text

soup = BeautifulSoup(info, 'html.parser')
songs = soup.select("li ul li h3")
song = [names.getText().strip() for names in songs]

sp = spotipy.Spotify(
    auth_manager=SpotifyOAuth(
        scope="playlist-modify-private",
        redirect_uri="https://example.com/",
        client_id=SPOTIFY_ID,
        client_secret=SPOTIFY_SECRET,
        show_dialog=True,
        cache_path="token.txt",
        username="312almnfdpfxhvftxcslexfzyfhu",
    )
)
user_id = sp.current_user()["id"]

song_list = []
year = date_input.split("-")[0]
print(year)

for i in song:
    result = sp.search(q=f'track:{i} year:{year}', limit=1, type='track', market="US")
    try:
        uri = result['tracks']['items'][0]['uri']
        song_list.append(uri)
    except IndexError:
        print(f"{i} doesn't exist in spotify. Skipped")

playlist_make = sp.user_playlist_create(
    user=user_id,
    name=f'{date_input} Billboard Top 100',
    public=False,
    description=f'The top song generated by febstar using python. Twitter:@febechukwu_owen'
)


sp.user_playlist_add_tracks(
    user=user_id,
    playlist_id=playlist_make["id"],
    tracks=song_list
)
